version: '3.4'

services:
  assigmentdb:
    container_name: assigmentdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  dayschedulerapp.api:
    container_name: assigment.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - "DaySchedulerDatabase:ConnectionString=mongodb://assigmentdb:27017"
      - Serilog__MinimumLevel=Information
      - Serilog__WriteTo__0__Name=Console
      - Serilog__WriteTo__1__Name=MongoDBBson
      - Serilog__WriteTo__1__Args__databaseUrl=mongodb://assigmentdb:27017/DayScheduler
      - Serilog__WriteTo__1__Args__collectionName=log
      - Serilog__WriteTo__1__Args__cappedMaxSizeMb=25
      - Serilog__WriteTo__1__Args__cappedMaxDocuments=1000
      - Serilog__WriteTo__1__Args__restrictedToMinimumLevel=Warning
    depends_on:
      - assigmentdb
    ports:
      - "8000:80"
      - "9000:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro